- name: Swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: Swarm master
  command: "docker swarm init --advertise-addr {{ansible_default_ipv4.address}}"
  when: "'active' not in swarm_status.stdout_lines"

- name: Swarm token
  command: "docker swarm join-token -q worker"
  register: swarm_token

- set_fact: swarmtoken="{{swarm_token.stdout}}"
