- hosts: all
  remote_user: "admin"
  become: yes
  become_method: sudo
  roles:
    - role: docker

- hosts: manager
  remote_user: "admin"
  become: yes
  become_method: sudo
  roles:
    - role: swarm-master
    - role: traefik

- hosts: nodes
  remote_user: "admin"
  become: yes
  become_method: sudo
  roles:
    - role: swarm-node
