- hosts: all
  remote_user: "root"
  vars_files:
    - vars.yml
  roles:
    - role: common
    - role: custom-kernel
    - role: docker

- hosts: manager
  remote_user: "root"
  vars_files:
    - vars.yml
  roles:
    - role: nfs-server
    - role: swarm-master
    - role: traefik
    - role: portainer

- hosts: nodes
  remote_user: "root"
  vars_files:
    - vars.yml
  roles:
    - role: nfs-mount
    - role: swarm-node
