- hosts: all
  remote_user: "admin"
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - role: docker

- hosts: manager
  remote_user: "admin"
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - role: swarm-master
    - role: traefik
    - role: portainer

- hosts: nodes
  remote_user: "admin"
  become: yes
  become_method: sudo
  vars_files:
    - vars.yml
  roles:
    - role: swarm-node
