- name: Swarm status
  shell: >
    docker info | egrep '^Swarm: ' | cut -d ' ' -f2
  register: swarm_status

- name: Cluster join
  command: "docker swarm join --advertise-addr {{ansible_default_ipv4.address}} --token {{hostvars[groups['manager'][0]].swarmtoken}} {{hostvars[groups['manager'][0]].inventory_hostname}}:2377"
  when: "'active' not in swarm_status.stdout_lines"
