- name: NFS package installation
  pacman:
    name: nfs-utils
    state: latest

- name: Shared folder creation
  file:
    path: /var/download-data
    state: directory

- name: NFS mount
  mount:
    name: /var/download-data
    src: "{{ download_nfs_host }}:/download-data"
    fstype: nfs
    opts: rw
    dump: 0
    passno: 2
    state: mounted
