- name: Reboot server
  listen: reboot server
  shell: sleep 2 && systemctl reboot
  async: 0
  poll: 0


- name: wait for server to come back
  listen: reboot server
  local_action: wait_for
  args:
    host: "{{ ansible_ssh_host }}"
    port: 22
    state: started
