- name: Restart portainer
  command: >
    docker service rm portainer &&
    docker service create
    --name portainer
    --label "traefik.port=9000"
    --label "traefik.frontend.rule=Host:<redacted>"
    --constraint 'node.role == manager'
    --network traefik-network
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock
    portainer/portainer
    -H unix:///var/run/docker.sock
  listen: restart portainer
