- name: Docker installation
  pacman:
    name: docker
    state: latest

- name: Docker compose installation
  pacman:
    name: docker-compose
    state: latest

- name: Docker group
  group:
    name: docker
    gid: 9000
    state: present

- name: Docker user
  user:
    name: docker
    group: docker
    uid: 9000
    state: present

- name: Docker configuration folder
  file:
    path: /etc/docker
    state: directory

- name: Docker configuration
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Docker keys
  copy:
    src: certs/
    dest: /etc/docker/certs/

- name: Docker service unit
  copy:
    src: docker.service.d/
    dest: /etc/systemd/system/docker.service.d/
  notify: restart docker

- name: Docker service start
  systemd:
    daemon-reload: true
    name: docker
    state: started
    enabled: yes
